---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hiphops-worker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hiphops-worker
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/exec
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiphops-worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hiphops-worker
subjects:
- kind: ServiceAccount
  name: hiphops-worker
  namespace: default
