apiVersion: apps/v1
kind: Deployment
metadata:
  name: hops
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: hops
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: hops
    spec:
      serviceAccountName: hops-worker
      containers:
        - name: hops
          image: "hiphops/hiphops:{{ .Values.hiphops.imageVersion }}"
          command: ["/hops"]
          args: ["start", "--address=0.0.0.0:8916", "--keyfile=/root/hiphops-key/hiphops.key", "--hops=/root/hops-conf/", "--serve-k8sapp"]
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8916

          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi

          startupProbe:
            httpGet:
              path: /health
              port: 8916
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8916
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8916
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1

          volumeMounts:
            - name: hiphops-key
              mountPath: {{ include "hiphops.path" "hiphops-key" }}
            {{- include "hiphops.automationVolumeMounts" . | trim | nindent 12 }}

      volumes:
        - name: hiphops-key
          secret:
            secretName: hiphops-key
        {{- include "hiphops.automationVolumes" . | trim | nindent 8 }}
